### PR TITLE
[JS-951] fix: use ember-local-storage for both read & write FF

### LINKED ISSUE #111: [JS-951] ember-local-storage config is not correctly handle when not default
Features values are not correctly restored by instance-initializer when `ember-local-storage` is used with `namespace` or  `keyDelimiter` options.

The reason is :

feature-controls component uses `storageFor` from `ember-local-storage` to write values in locale Store (https://github.com/peopledoc/ember-feature-controls/blob/master/addon/components/feature-controls.js#L6). 
`storageFor` take into account the `ember-local-storage` config to write the key at the right place in locale storage (with correct namespace and/or delimiter).

In other hand, the instance initializer uses `getStorage` & get value with the `storage:feature-controls` key wich does not take into account the `ember-local-storage` config (https://github.com/peopledoc/ember-feature-controls/blob/master/addon/instance-initializers/load-feature-controls.js#L9)

It results with a desynchronisation between `ember-feature-controls` & `ember-feature-flags` as the value are not correctly restored onto `ember-feature-flags` `features` service.

### PR DESCRIPTION
**Pull request by romgere**
###  Use `ember-local-storage` for both read & write FF to prevent issue when `ember-local-storage` options differents from default (#112)

This fix #111

### CODE REVIEW

File: addon/instance-initializers/load-feature-controls.js [hunk 1]
```diff
@@ -1,21 +1,21 @@
...
-        Object.keys(flags).forEach(flag => {
-          if (features.get("flags").includes(flag)) {
-            flags[flag] ? features.enable(flag) : features.disable(flag)
-          }
-        })
-      }
+
+    const controlStorageService = appInstance.lookup("service:feature-control-storage")
+    // result of controlStorageService.get('featuresLS') is an ObjectProxy we need to use "content"
+    let { content: featureControls } = controlStorageService.get('featuresLS')
```
Comment (MrChocolatine) [inline addon/instance-initializers/load-feature-controls.js:11]: I am surprised, you need to destruct `content` otherwise it does not work?

Because I compare this `featuresLS` (which is a `ObjectProxy` as you say) to the Service [`embedded` from our add-on `ember-cli-embedded`](https://github.com/peopledoc/ember-cli-embedded/blob/8367845de9be87f269ee4057fd6fee378a8a69b2/addon/services/embedded.ts) which also extends `ObjectProxy`. (for the record on RPA HR [we typed it like this](https://github.com/peopledoc/synapps-hr-admin-front/blob/e35eac8f6ab17a27b138ccc11916963b399272e5/types/peopledoc/ember-cli-embedded/index.d.ts))

And all the Tribe has been using this Service such as `this.embedded.get('something')` for instance:

- in [`/app/adapters/application.ts`](https://github.com/peopledoc/synapps-hr-admin-front/blob/e35eac8f6ab17a27b138ccc11916963b399272e5/app/adapters/application.ts)

```ts
export default class ApplicationAdapter extends PDAdapter {
  @service
  declare embedded: IServiceEmbedded

  get host(): string | undefined {
    return this.embedded.get('host')
  }

  get namespace(): string | undefined {
    return this.embedded.get('namespace')
  }
}
```

- in [`/app/router.js`](https://github.com/peopledoc/synapps-hr-admin-front/blob/e35eac8f6ab17a27b138ccc11916963b399272e5/app/router.js)

```js
export default class Router extends EmberRouter {
  @service embedded

  location = config.locationType

  // Use the `rootURL` provided by the host, when the app is started (see `index.html`)
  get rootURL() {
    return this.embedded.get('rootURL')
  }
}
```

File: addon/services/feature-control-storage.js [hunk 2]
```diff
@@ -0,0 +1,6 @@
+import Service from '@ember/service'
```
Comment (MrChocolatine) [inline addon/services/feature-control-storage.js:1]: Am I right saying that you created this Service, with only 1 property, just to make it easier to mock it during tests?

File: addon/instance-initializers/load-feature-controls.js [hunk 3]
```diff
@@ -1,21 +1,21 @@
...
+    if (featureControls) {
+      Object.keys(featureControls).forEach(flag => {
+        if (features.get("flags").includes(flag)) {
+          featureControls[flag] ? features.enable(flag) : features.disable(flag)
+        }
+      })
+      
     }
```
Comment (MrChocolatine) [inline addon/instance-initializers/load-feature-controls.js:19]: Simple suggestion not necessary of course 👍🏻 .
- Without `if`
- Direct access to flags value

But I admit `Object.entries()` is less supported than `Object.keys`.

```suggestion
    let featureControls = controlStorageService.get('featuresLS').content ?? {}

    Object.entries(featureControls).forEach(([ flag, flagValue ]) => {
      if (features.flags.includes(flag)) {
        flagValue ? features.enable(flag) : features.disable(flag)
      }
    })
```

**Review by MrChocolatine — APPROVED** [review]

File: addon/services/feature-control-storage.js (hunk 2 above)
Comment (romgere) [reply addon/services/feature-control-storage.js:1]: Nope, the purpose of this property is to be read from `instance-initializers/load-feature-controls.js` & keeping consistency between read & write on local-storage....

In other words, I didn't find the way to properly take into account the `ember-local-storage` settings in `instance-initializers` when reading from local-storage without using this service...
